version: '3.1'

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
volumes:
  db:
    driver: local
    external: false
