version: '3.1'

services:
  postgres:
    image: postgres:15.0-alpine
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgresql:/var/lib/postgresql/data
      - ./db/init-database.sql:/docker-entrypoint-initdb.d/init-database.sql
volumes:
  postgresql:
    driver: local
    external: false
